openapi: 3.0.1
info:
  title: An include file to define a generic IRIDA ResourceCollection
  version: 0.1.0
paths: {}
components:
  schemas:
    Project:
      properties:
        name:
          type: string
        createdDate:
          type: integer
        modifiedDate:
          type: integer
        assembleUploads:
          type: boolean
        label:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        identifier:
          type: integer
