openapi: 3.0.1
info:
  title: An include file to define a generic IRIDA Resource
  version: 0.1.0
paths: {}
components:
  schemas:
    Resource:
      properties:
        resource:
          type: object
