openapi: 3.0.1
info:
  title: An include file to define the root IRIDA resource
  version: 0.1.0
  termsOfService: 'https://raw.githubusercontent.com/phac-nml/irida/master/LICENSE'
paths: {}
components:
  schemas:
    RootResource:
      properties:
        resource:
          $ref: '#/components/schemas/LinkCollection'
