openapi: 3.0.1
info:
  title: An include file to define the root IRIDA resource
  version: 0.1.0
paths: {}
components:
  schemas:
    RootResource:
      properties:
        resource:
          $ref: '#/components/schemas/LinkCollection'
